### ISSUE TITLE
When I click "back" in my browser, it downloads the compare page?

### ISSUE THREAD

**Issue by macadellic** [nugget-dank-data/frontend#14]
You can recreate by navigating to the compare page. Then, click out of the page, then clicking 'back' in your browser.

![Screenshot 2023-09-15 at 4 32 37 PM](https://github.com/nugget-dank-data/frontend/assets/68249505/9bc45a16-6cf6-46d0-80ec-1ca96e712d00)

**Comment by macadellic** [comment]
Seems to happen with most pages if navigated to by the 'back' button
![Screenshot 2023-09-15 at 4 34 50 PM](https://github.com/nugget-dank-data/frontend/assets/68249505/e0678ccf-ec20-4175-b562-c5900ba94df9)

**Comment by Goodness5** [comment]
issue fixed
